/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models


/**
 * 
 * Values: 0,1,2,3,4
 */
enum class CouponState(val value: Int){
    UNKNOWN(0),
    ACTIVE(1),
    EXPIRED(2),
    REDEEMDED(3),
    WON(4);


    companion object{
        fun getCouponState(value: Int): CouponState? {
            return CouponState.values().find { couponState ->
                couponState.value == value
            }
        }
    }
}