/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json
import org.joda.time.DateTime

/**
 * 
 * @param id Alert identifier
 * @param name Alert name
 * @param body Alert body
 * @param publishDate Alert publish date
 * @param read Is the alert read?
 * @param registerId Register identifier
 * @param registerEntity Register entity name.  - News  - Campaign
 * @param complements 
 */
data class AlertListItem (

    /* Alert identifier */
    @field:Json(name = "id")val id: kotlin.String? = null,
    /* Alert name */
    @field:Json(name = "name")val name: kotlin.String? = null,
    /* Alert body */
    @field:Json(name = "body")val body: kotlin.String? = null,
    /* Alert publish date */
    @field:Json(name = "publishDate")val publishDate: DateTime? = null,
    /* Is the alert read? */
    @field:Json(name = "read")val read: kotlin.Boolean? = null,
    /* Register identifier */
    @field:Json(name = "registerId")val registerId: kotlin.String? = null,
    /* Register entity name.  - News  - Campaign */
    @field:Json(name = "registerEntity")val registerEntity: kotlin.String? = null,
    @field:Json(name = "complements")val complements: ComplementList? = null
) {
}