/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json


/**
 * 
 * @param accessToken Access token that identifies the user
 */
data class Bind (

    /* Access token that identifies the user */
    @field:Json(name = "accessToken")val accessToken: kotlin.String? = null
) {
}