/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json


/**
 * 
 * @param originUserHash Hash that identifies the user in the SSO of the source application
 * @param idDevice Device identifier for sending Push notifications
 * @param tokenPush Device token for sending Push notifications
 * @param deviceOS Device operating system
 */
data class BindRequest (

    /* Hash that identifies the user in the SSO of the source application */
    @field:Json(name = "originUserHash")val originUserHash: kotlin.String? = null,
    /* Device identifier for sending Push notifications */
    @field:Json(name = "idDevice")val idDevice: kotlin.String? = null,
    /* Device token for sending Push notifications */
    @field:Json(name = "tokenPush")val tokenPush: kotlin.String? = null,
    /* Device operating system */
    @field:Json(name = "deviceOS")val deviceOS: kotlin.String? = null
) {
}