/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json


/**
 * 
 * @param name 
 * @param progressChanged 
 * @param file 
 * @param currentFolderPath 
 * @param idI 
 * @param userIdI 
 * @param langIdI 
 * @param entIdI 
 * @param entityIdI 
 * @param complementTypeIdI 
 * @param complementSubtypeIdI 
 * @param tmpGuidNv 
 * @param fileManagerType 
 * @param fileManagerProvider 
 */
data class Body (

    @field:Json(name = "name")val name: kotlin.String? = null,
    @field:Json(name = "progressChanged")val progressChanged: kotlin.Any? = null,
    @field:Json(name = "file")val file: List<kotlin.Byte>? = null,
    @field:Json(name = "currentFolderPath")val currentFolderPath: kotlin.String? = null,
    @field:Json(name = "idI")val idI: kotlin.String? = null,
    @field:Json(name = "userIdI")val userIdI: kotlin.String? = null,
    @field:Json(name = "langIdI")val langIdI: kotlin.String? = null,
    @field:Json(name = "entIdI")val entIdI: kotlin.String? = null,
    @field:Json(name = "entityIdI")val entityIdI: kotlin.String? = null,
    @field:Json(name = "complementTypeIdI")val complementTypeIdI: kotlin.String? = null,
    @field:Json(name = "complementSubtypeIdI")val complementSubtypeIdI: kotlin.String? = null,
    @field:Json(name = "tmpGuidNv")val tmpGuidNv: kotlin.String? = null
) {
}