/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json

/**
 * 
 * @param listCampaignType List of type of campaigns
 * @param listCompany List of companies
 * @param listBadge List of badges
 */
data class CampaignFilter (

    /* List of type of campaigns */
    @field:Json(name = "listCampaignType")val listCampaignType: List<CampaignFilterCampaignType>? = null,
    /* List of companies */
    @field:Json(name = "listCompany")val listCompany: List<CampaignFilterCompany>? = null,
    /* List of badges */
    @field:Json(name = "listBadge")val listBadge: List<CampaignFilterBadge>? = null
) {
}