/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json


/**
 * 
 * @param id Campaign type id
 * @param idDecrypt Campaign type id decrypted
 * @param name Campaign type name
 */
data class CampaignFilterCampaignType (

    /* Campaign type id */
    @field:Json(name = "id")val id: kotlin.String? = null,
    /* Campaign type id decrypted */
    @field:Json(name = "idDecrypt")val idDecrypt: kotlin.Int? = null,
    /* Campaign type name */
    @field:Json(name = "name")val name: kotlin.String? = null
) {
}