/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json


/**
 * 
 * @param url Complement url.  In case of image three params can be added at the end of the url with this format @width@height@quality to get an image thumbnail.
 */
data class ComplementListItem (

    /* Complement url.  In case of image three params can be added at the end of the url with this format @width@height@quality to get an image thumbnail. */
    @field:Json(name = "url")val url: kotlin.String? = null
) {
}