/**
 * Third Party B4F Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.batura.b4fLibrary.rest.models

import com.squareup.moshi.Json
import org.joda.time.DateTime

/**
 * 
 * @param id Coupon identifier
 * @param state 
 * @param redeemed Is the smarttag redeemed?
 * @param redeemDate Smarttag redemption date
 * @param campaignId Campaign identifier
 * @param campaignName Campaign name
 * @param campaignShortDescription Campaign short description
 * @param campaignLongDescription Campaign long description
 * @param campaignPublishDate Campaign publish date
 * @param campaignStartDate Campaign start date
 * @param campaignEndDate Campaign end date
 * @param campaignCouponMaxEntry Max number of use for coupon campaign
 * @param campaignCouponMaxRedeemDate Max redeem date for coupon campaign
 * @param campaignCouponConfShop Must be confirmed by shop in coupon campaign?
 * @param campaignCouponCampaignCode Campaign code for coupon campaign
 * @param campaignRaffleMaxContestant Max number de contestant for raffle campaign
 * @param campaignRaffleDate Raffle date for raffle campaign
 * @param campaignRaffleCongratsWin Text shown for raffle winners
 * @param campaignTypeId Campaign type identifier
 * @param campaignComplements 
 * @param smarttagCode Smarttag nfc's code
 * @param badgeId Badge identifier
 * @param badgeReference Badge reference
 * @param badgeName Badge name
 * @param badgeDescription Badge description
 * @param productId Product identifier
 * @param productReference Product reference
 * @param productName Product name
 * @param productDescription Product description
 * @param productComplements 
 * @param company 
 */
data class CouponDetail (

    /* Coupon identifier */
    @field:Json(name = "id")val id: kotlin.String? = null,
    @field:Json(name = "state")val state: CouponState? = null,
    /* Is the smarttag redeemed? */
    @field:Json(name = "redeemed")val redeemed: kotlin.Boolean? = null,
    /* Smarttag redemption date */
    @field:Json(name = "redeemDate")val redeemDate: DateTime? = null,
    /* Campaign identifier */
    @field:Json(name = "campaignId")val campaignId: kotlin.String? = null,
    /* Campaign name */
    @field:Json(name = "campaignName")val campaignName: kotlin.String? = null,
    /* Campaign short description */
    @field:Json(name = "campaignShortDescription")val campaignShortDescription: kotlin.String? = null,
    /* Campaign long description */
    @field:Json(name = "campaignLongDescription")val campaignLongDescription: kotlin.String? = null,
    /* Campaign publish date */
    @field:Json(name = "campaignPublishDate")val campaignPublishDate: DateTime? = null,
    /* Campaign start date */
    @field:Json(name = "campaignStartDate")val campaignStartDate: DateTime? = null,
    /* Campaign end date */
    @field:Json(name = "campaignEndDate")val campaignEndDate: DateTime? = null,
    /* Max number of use for coupon campaign */
    @field:Json(name = "campaignCouponMaxEntry")val campaignCouponMaxEntry: kotlin.Int? = null,
    /* Max redeem date for coupon campaign */
    @field:Json(name = "campaignCouponMaxRedeemDate")val campaignCouponMaxRedeemDate: DateTime? = null,
    /* Must be confirmed by shop in coupon campaign? */
    @field:Json(name = "campaignCouponConfShop")val campaignCouponConfShop: kotlin.Boolean? = null,
    /* Campaign code for coupon campaign */
    @field:Json(name = "campaignCouponCampaignCode")val campaignCouponCampaignCode: kotlin.String? = null,
    /* Max number de contestant for raffle campaign */
    @field:Json(name = "campaignRaffleMaxContestant")val campaignRaffleMaxContestant: kotlin.Int? = null,
    /* Raffle date for raffle campaign */
    @field:Json(name = "campaignRaffleDate")val campaignRaffleDate: DateTime? = null,
    /* Text shown for raffle winners */
    @field:Json(name = "campaignRaffleCongratsWin")val campaignRaffleCongratsWin: kotlin.String? = null,
    /* Campaign type identifier */
    @field:Json(name = "campaignTypeId")val campaignTypeId: CampaignType? = null,
    @field:Json(name = "campaignComplements")val campaignComplements: ComplementList? = null,
    /* Smarttag nfc's code */
    @field:Json(name = "smarttagCode")val smarttagCode: kotlin.String? = null,
    /* Badge identifier */
    @field:Json(name = "badgeId")val badgeId: kotlin.String? = null,
    /* Badge reference */
    @field:Json(name = "badgeReference")val badgeReference: kotlin.String? = null,
    /* Badge name */
    @field:Json(name = "badgeName")val badgeName: kotlin.String? = null,
    /* Badge description */
    @field:Json(name = "badgeDescription")val badgeDescription: kotlin.String? = null,
    /* Product identifier */
    @field:Json(name = "productId")val productId: kotlin.String? = null,
    /* Product reference */
    @field:Json(name = "productReference")val productReference: kotlin.String? = null,
    /* Product name */
    @field:Json(name = "productName")val productName: kotlin.String? = null,
    /* Product description */
    @field:Json(name = "productDescription")val productDescription: kotlin.String? = null,
    @field:Json(name = "productComplements")val productComplements: ComplementList? = null,
    @field:Json(name = "company")val company: CompanyInfo? = null




) {


}